# Generated by Django 5.0.6 on 2024-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalulator_sredniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_przedmiotu', models.CharField(max_length=255)),
                ('lista_ocen', models.TextField()),
                ('średnia_ocen', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
